server:
  port: 80
spring:
  datasource:
    username: root
    password: root
    #?serverTimezone=UTC解决时区的报错
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

#eureka


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://192.168.72.1:7001/eureka/,http://192.168.1.3:7002/eureka/,http://192.168.247.1:7003/eureka/