server:
  port: 7002
eureka:
  instance:
    hostname: localhost #Eureka 服务端实例名字
  client:
    register-with-eureka: false #表示是否向eureka注册
    fetch-registry: false  #如果为false 则表示自己为注册中心
    service-url:
      defaultZone: http://192.168.72.1:7001/eureka/,http://192.168.247.1:7003/eureka/

